# This is used on Jenkins with Docker slaves to build
# We  use an ubuntu as base image to install and run required packages for docker, 
FROM ubuntu:18.04

# Install all the pre-requisits we need in the docker image
RUN apt-get update \
  && apt-get install -y qemu-user-static docker.io sudo bzip2 ccache
  
  



# We need to make sure any user jenkins uses has rights to execute docker
# We are setting this up for the first three "normal" uids
# Depending on your Jenkins setup you may need to change this.

RUN useradd -o -u 1000  jenkins1 && useradd -o -u 1001 jenkins2 && useradd -o -u 1002  jenkins3




RUN echo "jenkins1     ALL=(ALL) NOPASSWD: /usr/bin/docker" >> /etc/sudoers
RUN echo "jenkins2     ALL=(ALL) NOPASSWD: /usr/bin/docker" >> /etc/sudoers
RUN echo "jenkins3     ALL=(ALL) NOPASSWD: /usr/bin/docker" >> /etc/sudoers
