# /********************************************************************************
# * Copyright (c) 2022, 2023 Contributors to the Eclipse Foundation
# *
# * See the NOTICE file(s) distributed with this work for additional
# * information regarding copyright ownership.
# *
# * This program and the accompanying materials are made available under the
# * terms of the Apache License 2.0 which is available at
# * http://www.apache.org/licenses/LICENSE-2.0
# *
# * SPDX-License-Identifier: Apache-2.0
# ********************************************************************************/

# This is expected to be executed in the kuksa.val top-level directory

# This builds the databroker-cli

FROM messense/rust-musl-cross:x86_64-musl AS builder-amd64
ENV BUILDTARGET="x86_64-unknown-linux-musl"


FROM messense/rust-musl-cross:aarch64-musl AS builder-arm64
ENV BUILDTARGET="aarch64-unknown-linux-musl"

FROM builder-$TARGETARCH as builder
ARG TARGETARCH

RUN apt-get update && apt-get install -y protobuf-compiler \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

# This will speed up fetching the crate.io index in the future, see
# https://blog.rust-lang.org/2022/06/22/sparse-registry-testing.html
ENV CARGO_UNSTABLE_SPARSE_REGISTRY=true

RUN echo "Building for $TARGETARCH"
ENV SRC="/home/rust/src"
WORKDIR ${SRC}

ENV CARGO_NET_GIT_FETCH_WITH_CLI=true

ADD kuksa_databroker kuksa_databroker
ADD proto proto
ADD Cargo.toml Cargo.toml

# Creating BOM
RUN cargo install cargo-license
WORKDIR ${SRC}/kuksa_databroker/createbom
RUN rm -rf ../thirdparty
RUN python3 createbom.py ../databroker-cli

WORKDIR ${SRC}/kuksa_databroker/databroker-cli

RUN cargo build --bin databroker-cli --release --target $BUILDTARGET
RUN mv ${SRC}/target/$BUILDTARGET/release/databroker-cli ${SRC}/

FROM  scratch

COPY --from=builder /home/rust/src/databroker-cli /app/databroker-cli
COPY --from=builder /home/rust/src/kuksa_databroker/databroker-cli/thirdparty /app/thirdparty
COPY --from=builder /lib/terminfo /etc/terminfo

ENTRYPOINT [ "/app/databroker-cli" ]
