name: spdx
description: Verify that files affected by a PR include SPDX license headers

branding:
  icon: zap
  color: gray-dark

inputs:
  files:
    description: >
      A comma-separated list of all files to check.
    default: ''
  licenses:
    description: >
      A space-separated list of all accepted licenses. For example:

      Apache-2.0 MIT
    required: true
    default: ''
runs:
  using: "composite"
  steps:
    - run: $GITHUB_ACTION_PATH//verify-spdx-headers
      shell: bash
