# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sdv/databroker/v1/broker.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from gen_proto.sdv.databroker.v1 import types_pb2 as sdv_dot_databroker_dot_v1_dot_types__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1esdv/databroker/v1/broker.proto\x12\x11sdv.databroker.v1\x1a\x1dsdv/databroker/v1/types.proto\"*\n\x14GetDatapointsRequest\x12\x12\n\ndatapoints\x18\x01 \x03(\t\"\xb0\x01\n\x12GetDatapointsReply\x12I\n\ndatapoints\x18\x01 \x03(\x0b\x32\x35.sdv.databroker.v1.GetDatapointsReply.DatapointsEntry\x1aO\n\x0f\x44\x61tapointsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12+\n\x05value\x18\x02 \x01(\x0b\x32\x1c.sdv.databroker.v1.Datapoint:\x02\x38\x01\"!\n\x10SubscribeRequest\x12\r\n\x05query\x18\x02 \x01(\t\"\x9c\x01\n\x0eSubscribeReply\x12=\n\x06\x66ields\x18\x01 \x03(\x0b\x32-.sdv.databroker.v1.SubscribeReply.FieldsEntry\x1aK\n\x0b\x46ieldsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12+\n\x05value\x18\x02 \x01(\x0b\x32\x1c.sdv.databroker.v1.Datapoint:\x02\x38\x01\"#\n\x12GetMetadataRequest\x12\r\n\x05names\x18\x01 \x03(\t\"=\n\x10GetMetadataReply\x12)\n\x04list\x18\x01 \x03(\x0b\x32\x1b.sdv.databroker.v1.Metadata2\x9b\x02\n\x06\x42roker\x12_\n\rGetDatapoints\x12\'.sdv.databroker.v1.GetDatapointsRequest\x1a%.sdv.databroker.v1.GetDatapointsReply\x12U\n\tSubscribe\x12#.sdv.databroker.v1.SubscribeRequest\x1a!.sdv.databroker.v1.SubscribeReply0\x01\x12Y\n\x0bGetMetadata\x12%.sdv.databroker.v1.GetMetadataRequest\x1a#.sdv.databroker.v1.GetMetadataReplyb\x06proto3')



_GETDATAPOINTSREQUEST = DESCRIPTOR.message_types_by_name['GetDatapointsRequest']
_GETDATAPOINTSREPLY = DESCRIPTOR.message_types_by_name['GetDatapointsReply']
_GETDATAPOINTSREPLY_DATAPOINTSENTRY = _GETDATAPOINTSREPLY.nested_types_by_name['DatapointsEntry']
_SUBSCRIBEREQUEST = DESCRIPTOR.message_types_by_name['SubscribeRequest']
_SUBSCRIBEREPLY = DESCRIPTOR.message_types_by_name['SubscribeReply']
_SUBSCRIBEREPLY_FIELDSENTRY = _SUBSCRIBEREPLY.nested_types_by_name['FieldsEntry']
_GETMETADATAREQUEST = DESCRIPTOR.message_types_by_name['GetMetadataRequest']
_GETMETADATAREPLY = DESCRIPTOR.message_types_by_name['GetMetadataReply']
GetDatapointsRequest = _reflection.GeneratedProtocolMessageType('GetDatapointsRequest', (_message.Message,), {
  'DESCRIPTOR' : _GETDATAPOINTSREQUEST,
  '__module__' : 'sdv.databroker.v1.broker_pb2'
  # @@protoc_insertion_point(class_scope:sdv.databroker.v1.GetDatapointsRequest)
  })
_sym_db.RegisterMessage(GetDatapointsRequest)

GetDatapointsReply = _reflection.GeneratedProtocolMessageType('GetDatapointsReply', (_message.Message,), {

  'DatapointsEntry' : _reflection.GeneratedProtocolMessageType('DatapointsEntry', (_message.Message,), {
    'DESCRIPTOR' : _GETDATAPOINTSREPLY_DATAPOINTSENTRY,
    '__module__' : 'sdv.databroker.v1.broker_pb2'
    # @@protoc_insertion_point(class_scope:sdv.databroker.v1.GetDatapointsReply.DatapointsEntry)
    })
  ,
  'DESCRIPTOR' : _GETDATAPOINTSREPLY,
  '__module__' : 'sdv.databroker.v1.broker_pb2'
  # @@protoc_insertion_point(class_scope:sdv.databroker.v1.GetDatapointsReply)
  })
_sym_db.RegisterMessage(GetDatapointsReply)
_sym_db.RegisterMessage(GetDatapointsReply.DatapointsEntry)

SubscribeRequest = _reflection.GeneratedProtocolMessageType('SubscribeRequest', (_message.Message,), {
  'DESCRIPTOR' : _SUBSCRIBEREQUEST,
  '__module__' : 'sdv.databroker.v1.broker_pb2'
  # @@protoc_insertion_point(class_scope:sdv.databroker.v1.SubscribeRequest)
  })
_sym_db.RegisterMessage(SubscribeRequest)

SubscribeReply = _reflection.GeneratedProtocolMessageType('SubscribeReply', (_message.Message,), {

  'FieldsEntry' : _reflection.GeneratedProtocolMessageType('FieldsEntry', (_message.Message,), {
    'DESCRIPTOR' : _SUBSCRIBEREPLY_FIELDSENTRY,
    '__module__' : 'sdv.databroker.v1.broker_pb2'
    # @@protoc_insertion_point(class_scope:sdv.databroker.v1.SubscribeReply.FieldsEntry)
    })
  ,
  'DESCRIPTOR' : _SUBSCRIBEREPLY,
  '__module__' : 'sdv.databroker.v1.broker_pb2'
  # @@protoc_insertion_point(class_scope:sdv.databroker.v1.SubscribeReply)
  })
_sym_db.RegisterMessage(SubscribeReply)
_sym_db.RegisterMessage(SubscribeReply.FieldsEntry)

GetMetadataRequest = _reflection.GeneratedProtocolMessageType('GetMetadataRequest', (_message.Message,), {
  'DESCRIPTOR' : _GETMETADATAREQUEST,
  '__module__' : 'sdv.databroker.v1.broker_pb2'
  # @@protoc_insertion_point(class_scope:sdv.databroker.v1.GetMetadataRequest)
  })
_sym_db.RegisterMessage(GetMetadataRequest)

GetMetadataReply = _reflection.GeneratedProtocolMessageType('GetMetadataReply', (_message.Message,), {
  'DESCRIPTOR' : _GETMETADATAREPLY,
  '__module__' : 'sdv.databroker.v1.broker_pb2'
  # @@protoc_insertion_point(class_scope:sdv.databroker.v1.GetMetadataReply)
  })
_sym_db.RegisterMessage(GetMetadataReply)

_BROKER = DESCRIPTOR.services_by_name['Broker']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _GETDATAPOINTSREPLY_DATAPOINTSENTRY._options = None
  _GETDATAPOINTSREPLY_DATAPOINTSENTRY._serialized_options = b'8\001'
  _SUBSCRIBEREPLY_FIELDSENTRY._options = None
  _SUBSCRIBEREPLY_FIELDSENTRY._serialized_options = b'8\001'
  _GETDATAPOINTSREQUEST._serialized_start=84
  _GETDATAPOINTSREQUEST._serialized_end=126
  _GETDATAPOINTSREPLY._serialized_start=129
  _GETDATAPOINTSREPLY._serialized_end=305
  _GETDATAPOINTSREPLY_DATAPOINTSENTRY._serialized_start=226
  _GETDATAPOINTSREPLY_DATAPOINTSENTRY._serialized_end=305
  _SUBSCRIBEREQUEST._serialized_start=307
  _SUBSCRIBEREQUEST._serialized_end=340
  _SUBSCRIBEREPLY._serialized_start=343
  _SUBSCRIBEREPLY._serialized_end=499
  _SUBSCRIBEREPLY_FIELDSENTRY._serialized_start=424
  _SUBSCRIBEREPLY_FIELDSENTRY._serialized_end=499
  _GETMETADATAREQUEST._serialized_start=501
  _GETMETADATAREQUEST._serialized_end=536
  _GETMETADATAREPLY._serialized_start=538
  _GETMETADATAREPLY._serialized_end=599
  _BROKER._serialized_start=602
  _BROKER._serialized_end=885
# @@protoc_insertion_point(module_scope)
