name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with: 
        submodules: recursive
    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v3.5.0
      with:
        # list of Docker images to use as base name for tags
        images: |
          kuksa
        # generate Docker tags based on the following events/attributes
        tags: |
          type=ref,event=branch
          type=ref,event=pr
          type=semver,pattern={{version}}
          type=semver,pattern={{major}}.{{minor}}
          type=semver,pattern={{major}}
          type=sha
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Build dev env 
      uses: docker/build-push-action@v2
      with:
        file: docker/Dockerfile.dev
        context: .
        outputs: type=docker,dest=/tmp/kuksa-val-dev-ubuntu20.04-${{ steps.meta.outputs.version }}.tar
        push: ${{ github.event_name != 'pull_request' }}
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
    - name: Build kuksa-val docker
      uses: docker/build-push-action@v2
      with:
        platform: linux/amd64,linux/arm64
        file: docker/Dockerfile
        context: .
        outputs: type=docker,dest=/tmp/kuksa-val-${{ steps.meta.outputs.version }}.tar
        push: ${{ github.event_name != 'pull_request' }}
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
      name: docker kuksa-viss-client docker
      uses: docker/build-push-action@v2
      with:
        platform: linux/amd64,linux/arm64
        context: kuksa_viss_client
        outputs: type=docker,dest=/tmp/kuksa-viss-client-${{ steps.meta.outputs.version }}.tar
        push: ${{ github.event_name != 'pull_request' }}
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
    - name: build kuksa gps feeder docker
      uses: docker/build-push-action@v2
      with:
        platform: linux/amd64,linux/arm64
        context: kuksa_feeders/gps2val
        outputs: type=docker,dest=/tmp/kuksa-gps-feeder-${{ steps.meta.outputs.version }}.tar
        push: ${{ github.event_name != 'pull_request' }}
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
