name: CI

on:
  push:
    branches: [ master ]
    tags:
      - '0.*'
  pull_request:
    branches: [ master ]
    
jobs:
  buildAndTest:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with: 
        submodules: recursive
    - name: ci
      id: test
      uses: ./
    - name: listing test results
      run: ls -llR ${{ steps.executor.outputs.test }}
